# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source :gemcutter


gem "hoe-yard", ">=0.1.2", :group => [:development, :test]
gem "hpricot", ">=0", :group => [:development, :test]
gem "rspec", ">=0", :group => [:development, :test]
gem "cucumber", ">=0", :group => [:development, :test]
gem "guard-rspec", ">=0", :group => [:development, :test]
gem "guard-cucumber", ">=0", :group => [:development, :test]
gem "growl", ">=0", :group => [:development, :test]
gem "fakeweb", ">=0", :group => [:development, :test]
gem "hoe-gemspec", ">=0", :group => [:development, :test]
gem "hoe", "~>2.16", :group => [:development, :test]

# vim: syntax=ruby
