# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source :gemcutter


gem "rspec", ">=0", :group => [:development, :test]
gem "rdoc", "~>3.10", :group => [:development, :test]
gem "hoe", "~>2.16", :group => [:development, :test]

# vim: syntax=ruby
